# Site settings
title:       G1-2讨论班 Blog
# email:       
author:      bingchang
description: "The G1-2讨论班 Blog"
baseurl:     ""
url:         "http://taolunban.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: false
github_username:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
#markdown:     kramdown #redcarpet
permalink:    pretty
paginate:     3
sass:
  compressed: true


theme: jekyll-theme-midnight
